### PR TITLE
integration from visualfsharp master

### PR DESCRIPTION
**Pull request by ninjarobot**
@dsyme I appreciate the direction getting started with this.  I went through the steps pulling in two additional commits compared to #808, however 30 _fewer_ files were changed.  The difference seems to be the files being removed under src/fsharp/xlf.  Should I remove those as well?

One additional note, build succeeds but tests fail with the following - any suggestions or might this be my environment (Docker `mono:latest` image):
```
Running libtest....OK
Running int32....OK
Running attributes....OK
FAILURE: math/measures/test.fsx - System.InvalidProgramException: Invalid IL code in Core_genericMeasures:foo (): IL_0005: stloc.0   


  at Core_genericMeasures.RunAll () [0x00000] in <5a61567b229e38e0a74503837b56615a>:0 
  at Core_genericMeasures.RUN[a] () [0x00000] in <5a61567b229e38e0a74503837b56615a>:0 
  at Run-all+clo@108-1349.Invoke (Microsoft.FSharp.Core.Unit arg00@) [0x00002] in <5a61567b229e38e0a74503837b56615a>:0 
  at Run-all.check (System.String dir, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] f) [0x0000c] in <5a61567b229e38e0a74503837b56615a>:0 
```

### CODE REVIEW

**Comment by dsyme** [comment]
Unfortunately the OSX CI takes forever to complete, it's very frustrating. I'm not entirely sure why, though I suppose it's just that the free Travis OSX support is overloaded.

**Comment by dsyme** [comment]
@ninjarobot For simple integrations not involving any build file changes we can generally merge just based on successful Linux+Windows CI, though it's not ideal

**Comment by baronfel** [comment]
It looks like Travis is having issue with their Mac builds of all varieties, and will continue for the near future: https://www.traviscistatus.com/incidents/mc9x2wmpnvhg

**Comment by dsyme** [comment]
Could you add a separate issue about the failing test? I'd not seen that before. I normally only run tests via CI for integrations, perhaps it's been slipping through, or is debug-only or something. Thanks!

**Pull request merged**
