### PR TITLE
Add Linuxbrew

### PR DESCRIPTION
**Pull request by ShalokShalom**
This adds support for all distros

### CODE REVIEW

**Comment by ShalokShalom** [comment]
Fine, I see. 

Homebrew is already in the Readme, by the way. 

I created an issue [here](https://discourse.brew.sh/t/update-for-mono/2064), since I was unable to find the mentioned issues on both, Linuxbrew-core and Homebrew-core. 

Thanks a lot

**Comment by baronfel** [comment]
There are a few, here's one that links to other attempts: https://github.com/Homebrew/homebrew-core/pull/17435

The root problem is that building mono from souce is very hard, and we end up trying to recreate many packaging steps that they do, see previous discussions on homebrew about libgdiplus, msbuild, and the dotnet cli.  Fsharp needs msbuild, dotnet and other dependencies, and so now there need to be homebrew packages for those tools, etc.

**Comment by ShalokShalom** [comment]
And dotnetcore instead?

**Comment by baronfel** [comment]
I think using the dotnet core version of the compiler would be hard as well because there's not a homebrew formula for it yet, per this discussion: https://github.com/dotnet/cli/issues/533.  I'd imagine that linuxbrew can't use cask-based install methods, since those just run binary installers which may not exist for Linux, so we have to only look at build-from-source solutions.

**Comment by ShalokShalom** [comment]
It seems there is an experimental formula open?
https://github.com/brthor/homebrew-dotnet-cli/blob/master/Formula/dotnetcli.rb

**Comment by baronfel** [comment]
That's a very old version, from berfore version 1 of the client was completed. Most of the .net core ecosystem have moved on to version 2.0.x or now onto 2.1.x. that formula would eb a good place to start working from, though!

**Comment by ShalokShalom** [comment]
Yeah, he assumes [here](https://github.com/dotnet/cli/issues/533#issuecomment-379488787) that it works as it is for 2 too.

**Comment by ShalokShalom** [comment]
https://github.com/habitat-sh/core-plans/pull/1378

Habitat is an awesome package manager, available for Windows, Linux and macOS, with a company behind and they just updated their dotnetcore package, Mono is available too. 

If my commit would get accepted, can I try to build a package, their build scripts are like simpler versions of PKGBUILD, which one I use on my desktop. :)

**Comment by ShalokShalom** [comment]
Maybe we should mark it then as "searches for a maintainer" or something?

**Pull request merged**
