### PR TITLE
WIP Integrate visualfsharp master

### PR DESCRIPTION
**Pull request by dsyme**
An attempt to integrate the latest from visualfsharp master.

### CODE REVIEW

**Comment by dsyme** [comment]
This PR contains all the latest F# 4.1 work, plus crucially it also replaces the FSharpSource.targets and other project files to be essentially identical to that in http://github.com/Microsoft/visualfsharp.

If we manage to get this integration through it is a huge step towards totally and permanently aligning http://github.com/fsharp/fsharp and http://github.com/Microsoft/visualfsharp (where the latter still contains extra stuff like the Visual F# Tools integration, eventually to be split out)

There are still some small differences (e.g. the Mono version is stuck on using MSBuild 12.0 for the compiler-integrate-reference-resolver) but these could be easily folded back to http://github.com/Microsoft/visualfsharp

**Comment by dsyme** [comment]
Annoying error on Linux/Mac

```
		Created directory "obj/Proto/net40/"
		Executing: "/Users/travis/build/fsharp/fsharp/src/fsharp/FSharp.Build-proto/../../../packages/FSharp.Compiler.Tools.4.0.1.19/tools/fsi.exe" --exec "/Users/travis/build/fsharp/fsharp/src/scripts/fssrgen.fsx" "/Users/travis/build/fsharp/fsharp/src/fsharp/FSharp.Build/FSBuild.txt" "obj/Proto/net40/FSBuild.fs"  "obj/Proto/net40/FSBuild.resx" 
		/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/tmp580cc3fc.tmp: line 1: /Users/travis/build/fsharp/fsharp/src/fsharp/FSharp.Build-proto/../../../packages/FSharp.Compiler.Tools.4.0.1.19/tools/fsi.exe: cannot execute binary file
/Users/travis/build/fsharp/fsharp/src/scripts/fssrgen.targets: error : Command '"/Users/travis/build/fsharp/fsharp/src/fsharp/FSharp.Build-proto/../../../packages/FSharp.Compiler.Tools.4.0.1.19/tools/fsi.exe" --exec "/Users/travis/build/fsharp/fsharp/src/scripts/fssrgen.fsx" "/Users/travis/build/fsharp/fsharp/src/fsharp/FSharp.Build/FSBuild.txt" "obj/Proto/net40/FSBuild.fs"  "obj/Proto/net40/FSBuild.resx" ' exited with code: 126.
	Task "Exec" execution -- FAILED
```

I thought it was becaue of a missing ``chmod u+x`` on ``fsi.exe`` but that's now in place and the error is still happening

**Comment by smoothdeveloper** [comment]
@dsyme depending how mono is setup, calling fsi.exe through mono might work:

```
mono "/Users/travis/build/fsharp/fsharp/src/fsharp/FSharp.Build-proto/../../../packages/FSharp.Compiler.Tools.4.0.1.19/tools/fsi.exe" --exec "/Users/travis/build/fsharp/fsharp/src/scripts/fssrgen.fsx" "/Users/travis/build/fsharp/fsharp/src/fsharp/FSharp.Build/FSBuild.txt" "obj/Proto/net40/FSBuild.fs"  "obj/Proto/net40/FSBuild.resx"
```

**Comment by smoothdeveloper** [comment]
Maybe ubuntu is doing this http://www.mono-project.com/archived/guiderunning_mono_applications/#registering-exe-as-non-native-binaries-linux-only

we shouldn't rely on this being the case

**Comment by smoothdeveloper** [comment]
To do a quick check, in `before_install.sh`, you can change the calls to nuget by removing `mono` before it, and it should fail rather early in the build.

**Comment by dsyme** [comment]
@smoothdeveloper It's very odd because sometimes Mono seems to insert itself as the execution engine, and sometimes it doesn't. I thought it always did if the target binary was a .NET binary

**Comment by nosami** [comment]
I tried to use this PR on OSX and found a couple of problems :-


`Microsoft.FSharp.targets` is looking for `fsc.exe` at the wrong location
```
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/4.5/Microsoft.FSharp.targets: error : Tool executable '/Users/jason/src/monodevelop/main/build/bin/MSBuild/14.0/fsc.exe' could not be found
```

I hacked around that and then hit this error :-

```
		Unhandled Exception:
		System.TypeInitializationException: The type initializer for 'Microsoft.FSharp.Compiler.AbstractIL.IL' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Compiler>.$Microsoft.FSharp.Compiler.AbstractIL.IL' threw an exception. ---> System.TypeInitializationException: The type initializer for 'FastGenericComparerTable`1' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Core>.$Prim-types' threw an exception. ---> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "FSCore.resources" was correctly embedded or linked into assembly "FSharp.Core" at compile time, or that all the satellite assemblies required are loadable and fully signed.
		  at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing (System.String fileName) [0x000ca] in <829ce140006e4cad9124766ee7f51179>:0 
		  at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet (System.Globalization.CultureInfo culture, System.Collections.Generic.Dictionary`2[TKey,TValue] localResourceSets, System.Boolean tryParents, System.Boolean createIfNotExists, System.Threading.StackCrawlMark& stackMark) [0x00110] in <829ce140006e4cad9124766ee7f51179>:0 
		  at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo requestedCulture, System.Boolean createIfNotExists, System.Boolean tryParents, System.Threading.StackCrawlMark& stackMark) [0x000ad] in <829ce140006e4cad9124766ee7f51179>:0 
		  at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo culture, System.Boolean createIfNotExists, System.Boolean tryParents) [0x00002] in <829ce140006e4cad9124766ee7f51179>:0 
		  at System.Resources.ResourceManager.GetString (System.String name, System.Globalization.CultureInfo culture) [0x0006a] in <829ce140006e4cad9124766ee7f51179>:0 
		  at <StartupCode$FSharp-Core>.$Prim-types..cctor () [0x00010] in <5883befbdff9fae1a7450383fbbe8358>:0 
```

Looking at the Travis log, looks like the Localization target is missing. `	/home/travis/build/fsharp/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj:  warning : Target 'Localize', not found in the project`

**Comment by dsyme** [comment]
# Hallelujah it's green!

**Pull request merged**
