### PR TITLE
Add support for Xamarin.TVOS profile.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by dsyme** [comment]
It looks like Mono 4.2.1 fails one of the F# quotation tests - the reflection implementation fails to bind a getter property in a quotation, see https://travis-ci.org/fsharp/fsharp/jobs/91840519#L8354

The failure is unrelated to this PR

**Comment by rolfbjarne** [comment]
@dsyme Do I need to do something about that failure?

**Comment by dsyme** [comment]
No, though ideally we'd clear it through another PR (e.g. disable the test and report a bugzilla bug) before merging.

**Comment by haf** [comment]
Can we make the mono project run the F# unit tests before they release breaking changes into the eco-system at large?

**Comment by rneatherway** [comment]
I think it would definitely be nice if they did! We can't *make* them do anything though. We could ask if we can help them add an F# job to their [Jenkins instance](https://jenkins.mono-project.com/), or perhaps expand our matrix here with a job that builds latest mono from master (as long as it still takes under an hour).

**Comment by dsyme** [comment]
AFAIK they build F# - they surely have to as part of Mono releases - but yes, getting a build and test of F# into their CI would be absolutely great

**Comment by enricosada** [comment]
we can leave mono HEAD in the build matrix, but configure to [allow failure on mono HEAD](https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail
)

i'll send a pr

**Comment by rolfbjarne** [comment]
@enricosada was PR #523 the one you mention? If so, can we proceed with this one since #523 is closed now?

**Comment by enricosada** [comment]
About this pr i dont know, @dsyme has allowed failures on mono head because of a known bug, need to ask him

**Pull request merged**
