### PR TITLE
Allow building with deprecated xbuild

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by akoeplinger** [comment]
The property was added to xbuild in Mono 5.10, do we really need this?

**Comment by dsyme** [comment]
@akoeplinger That's good to know.

Xamarin Android testing was tripping over this, I'm not sure of the Mono being used, which branch etc.  

@nosami @directhex Please let me know either way

**Comment by nosami** [comment]
There were some other related issues with the Android build. 

- Missing F# in the GAC (by design) broke an msbuild task that was assuming it was there
- Outdated system Mono that didn't contain YieldDuringToolExecution property


I think this PR can be closed.

**Comment by dsyme** [comment]
ok, great, will close

**Pull request closed without merging**
