### PR TITLE
Fsharp/master

### PR DESCRIPTION
**Pull request by 7sharp9**
Added support for xamarinmac FSharp.Core profiles

### CODE REVIEW

**Comment by dsyme** [comment]
Should this add the new FSharp.Core dlls for these platforms to the nuget package specifications too?

**Comment by 7sharp9** [comment]
Only the Mac mobile one would actually work due to nuget not supporting profiles with multiple aspects.  We could add it in the future if it was needed but I suspect the F# templates will suffice for applications, and for libraries you would probably target pcl 78/259

**Comment by dsyme** [comment]
So am I correct in thinking that these FSharp.Core binaries will ship as part of the Xamarin support for F# itself?

**Comment by dsyme** [comment]
Dave, will this resolve this issue: https://github.com/fsharp/fsharp/issues/367?  Thanks

**Comment by 7sharp9** [comment]
@dsyme No idea, I thought that issue was to do with iOS.  

To be honest I don't follow what the issue is, I though http://blog.xamarin.com/how-to-update-nuget-packages-for-64-bit/ would resolve it.

**Pull request merged**
