### PR TITLE
Remove FSharp.Core from Mono gac

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by dsyme** [comment]
@directhex @nosami Could you review and approve please? Thanks

**Comment by dsyme** [comment]
@directhex @nosami Do we want this in/  I presume so?

**Comment by nosami** [comment]
I'll test this out today with various projects and report back. Does the `fsc source.fs` scenario need to work too?

**Comment by nosami** [comment]
One thing that definitely needs to be considered is that having a Mono compiled FSharp.Core helps with stack traces.

Would it be possible to use portable pdb in the FSharp.Core NuGet?

**Comment by dsyme** [comment]
> One thing that definitely needs to be considered is that having a Mono compiled FSharp.Core helps with stack traces. 

You mean having portable PDBs?

> Would it be possible to use portable pdb in the FSharp.Core NuGet?

I don't see why not (except perhaps download size) - add an issue for @KevinRansom in visualfsharp repo

**Comment by nosami** [comment]
OK... I've given this about as much testing as I can. I successfully built VS for Mac and all the Xamarin F# templates without any issues using this PR.

Also `fsharpc somefile.fs` works fine without FSharp.Core in the GAC.

I think that this is good to merge and will align Mono and Windows builds

**Comment by dsyme** [comment]
> fsharpc somefile.fs works...

I think that is because it makes a local copy of FSHarp.Core, as fsc.exe does on Windows too (we had previously turned off that behaviour on Mono)

**Comment by nosami** [comment]
> I think that is because it makes a local copy of FSHarp.Core

So it did - I never noticed that!

**Comment by dsyme** [comment]
> So it did - I never noticed that!

That

**Comment by KevinRansom** [comment]
It is my plan to move over to embedded portable pdbs for both desktop and coreclr builds at some point.

**Pull request merged**
