### PR TITLE
added trailing 0 for Xamarin + Paket compatibility

### PR DESCRIPTION
**Pull request by ctaggart**
see fsharp/fsharp#450
branches are versions, so nuspec files do not need suffix

### CODE REVIEW

**Comment by forki** [comment]
LGTM

**Comment by forki** [comment]
already tried it in paket. seems to work. :shipit:

**Comment by forki** [comment]
next step would be the compiler.tools package, right?

@dsyme is this ready?

**Comment by 7sharp9** [comment]
Having a tagged master for F#4 would be nice so that F#4 can start making its way into mono, iOS, android, and Mac

**Comment by ctaggart** [comment]
4.0.0.1 was tagged. FSharp.Core NuGet was published.

**Comment by 7sharp9** [comment]
If its an official release then someone official should let the mono team know to update their current tag to start the process.
//cc @dsyme

**Comment by ctaggart** [comment]
@forki Uploaded. https://www.nuget.org/packages/FSharp.Compiler.Tools/4.0.0.1

@7sharp9 Don did the tag. See https://github.com/fsharp/fsharp/issues/429#issuecomment-124252182

**Comment by 7sharp9** [comment]
There needs to be some official notification so that mono can update its tag etc.

**Comment by dsyme** [comment]
At the moment that happens by us emailing @migueldeicaza and @directhex. I'll do that.

**Pull request merged**
