### PR TITLE
Fsharp 4.1 pkgs

### PR DESCRIPTION
**Pull request by enricosada**
For version `4.1.0.0-rc1`

- `FSharp.Core` package:
  - [x] add signed 4.1 `FSharp.Core` assembly #659 
  - [x] add netstandard to `FSharp.Core` #566 
  - [x] add signed 4.1 `FSharp.Core` assembly (pcl)
- `FSharp.Compiler.Tools` package:
  - [x] add fsc published a F# framework dependent netcoreapp1.0 #663 
  - [x] add props to locate fsc
  - [ ] add props to locate specific framework fsc

the netstandard `FSharp.Core` and netcoreapp `fsc` are not committed in the repo, but downloaded from  signed [Microsoft.FSharp.Compiler.netcore](https://www.nuget.org/packages/Microsoft.FSharp.Compiler.netcore) and [Microsoft.FSharp.Core.netcore](https://www.nuget.org/packages/Microsoft.FSharp.Core.netcore) released by vf# team /cc @cartermp @KevinRansom . The version is pinned, so are safe and easy to update.

### CODE REVIEW

**Comment by enricosada** [comment]
fixed build of packages.
Was a false positive (nuget pack failed, but build succeded), because `monotouch` target was not build

**Comment by dsyme** [comment]
This is awesome.  Could you also add signed F# 4.1 copies of all the PCL FSHarp.Core.*?  I think they are needed?

**Comment by enricosada** [comment]
Sure @dsyme , cleaning up a bit atm, i dont want to commit assemblies if packages exists.
I'll check vs2017rc4 install for portable fsharp.core assemblies

**Comment by dsyme** [comment]
> , i dont want to commit assemblies if packages exists. I'll check vs2017rc4 install for portable fsharp.core assemblies

fair enough :)

**Comment by enricosada** [comment]
added signed fsharp.core 4.1 pcl (thx @piaste)
aligned xmldoc with the one shipped in vs2017rc4, mostly typos

**Comment by enricosada** [comment]
Ok @dsyme it's done.
The packages built from appveyor are tested in https://github.com/dotnet/netcorecli-fsc/pull/61

It's possible to create an `4.1.0-rc1` and put that in a myget dev feed? So i'll update my sdk PR, and i can continue to update templates in dotnetcli ( we are really near code freeze ;) )

**Comment by enricosada** [comment]
The `FSharp.Compiler.Tools` now contains both

- net framework in `tools/fsc.exe`
- .net core in in `build/netcoreapp1.0/fsc.dll`

After unzip of `FSharp.Compiler.Tools` the fsc can be run, like a normal .net core app, with 

```
dotnet build/netcoreapp1.0/fsc.dll --help
```

tested with rc3, rc4. but doesnt matter because require only the dotnet core runtime, not sdk.

Importing the  `FSharp.Compiler.Tools` package in an fsproj, with auto-import the `FscToolPath` and `FscToolFileName` property, setting up correct fsc.  or the props can be used to run fsc with `<Exec` if needed (like smoke tests)

**Pull request merged**
