### PR TITLE
Integrate visualfsharp master

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by dsyme** [comment]
@ninjarobot Yes, assuming travis is ok.  Mono 5.0.1 gave an error in PDB generation but that's quite old now and I think we can go ahead
```

  Stacktrace:
  
    at <unknown> <0xffffffff>
    at System.Reflection.Metadata.BlobBuilder.WriteUTF8 (string,bool) [0x00016] in <9044eaafac114c31983b75781b50d624>:0
    at System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddBlobUTF8 (string,bool) [0x00006] in <9044eaafac114c31983b75781b50d624>:0
    at Microsoft.FSharp.Compiler.AbstractIL.ILPdbWriter.serializeDocumentName@231 (System.Reflection.Metadata.Ecma335.MetadataBuilder,string) [0x0007c] in <5b8fe6e5c960099ba7450383e5e68f5b>:0
    at Microsoft.FSharp.Compiler.AbstractIL.ILPdbWriter.generatePortablePdb (bool,Microsoft.FSharp.Collections.FSharpList`1<string>,string,bool,Microsoft.FSharp.Compiler.AbstractIL.ILPdbWriter/PdbData,bool) [0x0017d] in <5b8fe6e5c960099ba7450383e5e68f5b>:0
    at Microsoft.FSharp.Compiler.AbstractIL.ILBinaryWriter.writeBinaryAndReportMappings (string,Microsoft.FSharp.Compiler.AbstractIL.IL/ILGlobals,Microsoft.FSharp.Core.FSharpOption`1<string>,Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Compiler.AbstractIL.ILBinaryWriter/ILStrongNameSigner>,bool,bool,bool,Microsoft.FSharp.Collections.FSharpList`1<string>,string,bool,bool,bool,bool,Microsoft.FSharp.Compiler.AbstractIL.IL/ILModuleDef,Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Compiler.AbstractIL.IL/ILAssemblyRef, Microsoft.FSharp.Compiler.AbstractIL.IL/ILAssemblyRef>) [0x00802] in <5b8fe6e5c960099ba7450383e5e68f5b>:0
    at Microsoft.FSharp.Compiler.AbstractIL.ILBinaryWriter.WriteILBinary (string,Microsoft.FSharp.Compiler.AbstractIL.ILBinaryWriter/options,Microsoft.FSharp.Compiler.AbstractIL.IL/ILModuleDef,Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Compiler.AbstractIL.IL/ILAssemblyRef, Microsoft.FSharp.Compiler.AbstractIL.IL/ILAssemblyRef>) [0x00000] in <5b8fe6e5c960099ba7450383e5e68f5b>:0
    at Microsoft.FSharp.Compiler.Driver.main4<a_REF> (Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Tuple`3<Microsoft.FSharp.Compiler.TcGlobals/TcGlobals, string, Microsoft.FSharp.Compiler.AbstractIL.IL/ILModuleDef>, Microsoft.FSharp.Core.Unit>>,Microsoft.FSharp.Compiler.Driver/Args`1<System.Tuple`8<a_REF, Microsoft.FSharp.Compiler.CompileOps/TcConfig, Microsoft.FSharp.Compiler.CompileOps/TcImports, Microsoft.FSharp.Compiler.TcGlobals/TcGlobals, Microsoft.FSharp.Compiler.ErrorLogger/ErrorLogger, Microsoft.FSharp.Compiler.AbstractIL.IL/ILModuleDef, string, System.Tuple`3<Microsoft.FSharp.Core.FSharpOption`1<string>, Microsoft.FSharp.Compiler.Driver/StrongNameSigningInfo, Microsoft.FSharp.Compiler.ErrorLogger/Exiter>>>) [0x00156] in <5b8fe6e5c960099ba7450383e5e68f5b>:0
    at Microsoft.FSharp.Compiler.Driver.typecheckAndCompile (Microsoft.FSharp.Compiler.AbstractIL.Internal.Library/CompilationThreadToken,string[],Microsoft.FSharp.Compiler.ReferenceResolver/Resolver,bool,Microsoft.FSharp.Compiler.AbstractIL.ILBinaryReader/ReduceMemoryFlag,Microsoft.FSharp.Compiler.CompileOps/CopyFSharpCoreFlag,Microsoft.FSharp.Compiler.ErrorLogger/Exiter,Microsoft.FSharp.Compiler.Driver/ErrorLoggerProvider,Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Compiler.CompileOps/TcImports, Microsoft.FSharp.Core.Unit>>,Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Tuple`3<Microsoft.FSharp.Compiler.TcGlobals/TcGlobals, string, Microsoft.FSharp.Compiler.AbstractIL.IL/ILModuleDef>, Microsoft.FSharp.Core.Unit>>) [0x00038] in <5b8fe6e5c960099ba7450383e5e68f5b>:0
    at Microsoft.FSharp.Compiler.Driver.mainCompile (Microsoft.FSharp.Compiler.AbstractIL.Internal.Library/CompilationThreadToken,string[],Microsoft.FSharp.Compiler.ReferenceResolver/Resolver,bool,Microsoft.FSharp.Compiler.AbstractIL.ILBinaryReader/ReduceMemoryFlag,Microsoft.FSharp.Compiler.CompileOps/CopyFSharpCoreFlag,Microsoft.FSharp.Compiler.ErrorLogger/Exiter,Microsoft.FSharp.Compiler.Driver/ErrorLoggerProvider,Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Compiler.CompileOps/TcImports, Microsoft.FSharp.Core.Unit>>,Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Tuple`3<Microsoft.FSharp.Compiler.TcGlobals/TcGlobals, string, Microsoft.FSharp.Compiler.AbstractIL.IL/ILModuleDef>, Microsoft.FSharp.Core.Unit>>) [0x00000] in <5b8fe6e5c960099ba7450383e5e68f5b>:0
    at Microsoft.FSharp.Compiler.CommandLineMain/Driver.main (string[]) [0x0008b] in <5b8fe6e5c960099ba7450383e5e68f5b>:0
    at Microsoft.FSharp.Compiler.CommandLineMain.main (string[]) [0x00041] in <5b8fe6e5c960099ba7450383e5e68f5b>:0
    at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) [0x00054] in <5b8fe6e5c960099ba7450383e5e68f5b>:0
  ```

**Comment by baronfel** [comment]
Would a new FSharp.Compiler.Tools package come out of this repo post-merge, or out of Microsoft/VisualFSharp?

**Comment by dsyme** [comment]
> Would a new FSharp.Compiler.Tools package come out of this repo post-merge, or out of Microsoft/VisualFSharp?


Out of here, it's really why I'm doing the integration

**Comment by dsyme** [comment]
Just tagged 10.1.2, appveyor should produce the new FCT package soon

**Comment by dsyme** [comment]
Whoops, needs more work, the wrong FSHarp.Core is being included.  Will report back

**Pull request merged**
