### PR TITLE
Simplify mono - remove use of autoconf

### PR DESCRIPTION
**Pull request by dsyme**
@nosami @directhex @knocte I'd like to remove the use of autoconf, which seems like overkill in this repo and causes problems on OSX since you have to homebrew that tool.

The attached gets the prefix from the location of the `mono` command, and assumes that `mono` and `msbuild` are on the command line

See also https://github.com/Microsoft/visualfsharp/pull/4358, more or less the same commit in visualfsharp repo

### CODE REVIEW

**Comment by knocte** [comment]
Removing autoconf is fine by me so long as you still have a "configure" script that checks for dependencies. You could even code it as an .fsx script (I have an example of this approach in this project if you're curious: https://github.com/knocte/gwallet ).

**Comment by dsyme** [comment]
> Removing autoconf is fine by me so long as you still have a "configure" script that checks for dependencies. 

I've removed all trace of `configure`.  If you need something like that please add whatever dependency checking you want into the Makefile.  The checks on dependencies were largely out of date in any case (checking for Mono 4.0 when Mono 5.0 is actually needed)

**Comment by nosami** [comment]
@dsyme If you build Mono yourself into a custom prefix, fsharp/fsharp isn't installed inside of it (neither is anything else such as msbuild). 

Looks like you might have disabled one of the mechanisms I use to test Mono fixes for F#. I would always build Mono into a custom prefix for testing.

**Comment by knocte** [comment]
Yes, configuration phase is not only to check dependencies, @nosami good point. This would also make it impossible to create debian packages for F#.

**Comment by knocte** [comment]
> The checks on dependencies were largely out of date in any case (checking for Mono 4.0 when Mono 5.0 is actually needed)

If they were out of date, they should have been fixed, not removed. By being removed, now someone might install F# with even Mono 3.x, only to find later that it doesn't work.

**Comment by dsyme** [comment]
To use a custom prefix use

    make prefix=whatever

thanks

**Comment by directhex** [comment]
Does this allow for staging?

Lets's say you build bakes `$prefix` into itself, e.g. the `fsharpi` launch script hardcodes `$prefix/lib/fsharp/fsi.exe`

During package build, you need to stage the package in a temporary directory, e.g. `$CURDIR/debian/tmp`, such that `$CURDIR/debian/tmp/bin/fsharpi` contains hardcoded references to `$prefix/lib/fsharp/fsi.exe`

Usually, this is accomplished by passing a `DESTDIR=` value to `make install`

Is this still possible?

**Comment by dsyme** [comment]
@directhex Yes, you can pass DESTDIR to `make install`.  

If you guys need to make changes please do.   Just don't bring back autoconf

**Pull request merged**
