### PR TITLE
Move bootstrap LKG to be F# 4.0

### PR DESCRIPTION
**Pull request by forki**
from my C:\Users\Steffen\AppData\Local\Microsoft\VisualStudio\12.0FSharp\Extensions\Microsoft.VisualFSharpTools\Microsoft.VisualFSharpTools.EnableOpenSource\4.0

### CODE REVIEW

**Comment by forki** [comment]
FSC: error FS0219: The referenced or default base CLI library 'mscorlib' is binary-incompatible with the referenced F# core library '/usr/lib/mono/gac/FSharp.Core/4.3.1.0__b03f5f7f11d50a3a/FSharp.Core.dll'. Consider recompiling the library or making an explicit reference to a version of this library that matches the CLI version you are using.
    	FSC: error FS0218: Unable to read assembly '/usr/lib/mono/gac/FSharp.Core/4.3.1.0__b03f5f7f11d50a3a/FSharp.Core.dll'

**Comment by forki** [comment]
C:\projects\fsharp\lib\bootstrap\4.0\Microsoft.FSharp.Targets(204,5): error MSB6004: The specified task executable location "C:\projects\fsharp\src\fsharp\FSharp.Core\..\..\..\lib\proto\fsc-proto.exe" is invalid. 

/cc @dsyme

**Comment by dsyme** [comment]
Not sure what the errors are (we should sort that out). But in any case, this is a PR to update the bootstrap LKG, which is oK but not time-critical.  What we were discussing was something different - a PR to add the various signed FSharp.Core editions for F# 4.0 under https://github.com/fsharp/fsharp/tree/fsharp4/lib/bootstrap/signed

**Comment by dsyme** [comment]
Let's keep this PR and start a new one. I'll rename this one

**Comment by forki** [comment]
ah I see. then I better wait a bit ;-)

**Comment by dsyme** [comment]
@forki - no need to wait - just start a new PR with the FSharp.Core taken from the reference assemblies of a vS2015 install

**Comment by forki** [comment]
ok see https://github.com/fsharp/fsharp/pull/454

**Comment by dsyme** [comment]
Closing as it is old, we can grab the LKG from the Visual F# Tools at some point

**Pull request closed without merging**
