### PR TITLE
stable versions created from Git tags

### LINKED ISSUE #434: create stable builds using AppVeyor from Git tag
#433 makes all the builds pre-release NuGet builds. I am proposing that the stable NuGet builds be done from AppVeyor as well. I do this for my open source and work projects. The AppVeyor NuGet project feed may be used for testing the builds. If a stable build fails testing, you can delete and then re-add the Git tag. AppVeyor will replace the file in the nupkg in the feed.

The changes to appveyor.ps1 would be pretty simple.
```
if ($env:appveyor_repo_tag -eq 'true' -and isVersionTag($env:appveyor_repo_tag_name)){
```

We would just need to agree upon what locally the `isVersionTag` is. I don't currently understand how this repo is being tagged:
image

Why aren't there any `3.1.2.x` builds? Why are there so many? Are some unstable builds? Does the change log only have the stable builds?
https://github.com/fsharp/fsharp/blob/master/CHANGES.txt

### PR DESCRIPTION
**Pull request by ctaggart**
This continues #433 and fixes #434.

### CODE REVIEW

**Comment by dsyme** [comment]
I merged, then bumped to 3.1.2.3, then pushed the tag.

**Comment by ctaggart** [comment]
# Stable Build Release Candidate

Yay! We have a `3.1.2.3` build that can be tested.

image

`nuget install FSharp.Core -source https://ci.appveyor.com/nuget/fsgit-fsharp`

image

# Build History

The build history looks great!

https://ci.appveyor.com/project/fsgit/fsharp/history

image

# Next Pre-release Versions

In order to have the next builds be `3.1.2.4-b210` etc instead of `3.1.2.3-b210`, you just need to bump the version in the `build.ps1`. A tag ignores the version in there. It is just for the pre-release builds.

**Comment by ctaggart** [comment]
If you are using Paket, just add the source to the top of `paket.dependencies`:

```
source https://www.nuget.org/api/v2
source https://ci.appveyor.com/nuget/fsgit-fsharp

nuget FSharp.Core 3.1.2.3
```

Then run `.\paket.exe install`.

**Comment by amazingant** [comment]
This looks great so far, @ctaggart :)

**Comment by dsyme** [comment]
@ctaggart - Can you add this info to README.md please? thanks

**Comment by dsyme** [comment]
@ctaggart - if you could also send a PR to https://github.com/fsharp/FSharp.Compiler.Service/ to also publish a nuget package feed there, that would be awesome.

In that case, if there is some way to read the version number from RELEASE_NOTES.md that would be much appreciated.

**Pull request merged**
