### PR TITLE
[WIP] update travis

### PR DESCRIPTION
**Pull request by enricosada**
- [ ] travis

### CODE REVIEW

**Comment by dsyme** [comment]
@enricosada Thanks, this is great. I really want to get everything green again.  Then I want to see all trace of project.json disappear ASAP :)

**Comment by dsyme** [comment]
@enricosada The failures on travis are due to all OSX builds failing to download the Mono MDK in a timely way during startup, see ``https://travis-ci.org/fsharp/fsharp/jobs/215567042``

This seems to be a problem across the board in all repos doing Travis CI testing on Mono

**Comment by dsyme** [comment]
@enricosada (We don't currently do any .NET Core build/test in this repo on OSX or Linux)

**Comment by dsyme** [comment]
So I think we should merge up to https://github.com/fsharp/fsharp/pull/688/commits/3f960bed5adfcebf0cc89f413cfe620f52b3598d and then  mark OSX + Mono as a known failure for now (sadly). Unless we know how to fix that.

**Comment by enricosada** [comment]
let me check, maybe is the travis build worker. 
for others repos mono works afaik (had some issue some days ago but was fixed)

**Comment by dsyme** [comment]
@enricosada Thanks

**Comment by dsyme** [comment]
@enricosada I will cherry-pick up to 3f960be in order to get AppVeyor back up

**Comment by dsyme** [comment]
@enricosada OK those AppVeyor changes are merged - this PR is now only about Travis (thanks!)

**Comment by dsyme** [comment]
@enricosada Note that we don't do any .NET Core build/test in this repo on OSX or Linux - so I don't think you need to have any ``dotnet`` declaration in travis.yml at all?

**Comment by enricosada** [comment]
Ah yes, i am doing useless work :D
thanks for warning.. i am used to add netcore, maybe too much

**Comment by dsyme** [comment]
@enricosada Yes, the only problem we have left is this Mono thing:

> The failures on travis are due to all OSX builds failing to download the Mono MDK in a timely way during startup, see https://travis-ci.org/fsharp/fsharp/jobs/215567042..... This seems to be a problem across the board in all repos doing Travis CI testing on Mono

**Comment by dsyme** [comment]
@enricosada I'll close this for now - if you know how to fix [this problem](https://github.com/fsharp/fsharp/pull/688#issuecomment-289528577) to give us CI coverage on OSX again I'd be really grateful

**Pull request closed without merging**
