### PR TITLE
FSharp.Core taken from the reference assemblies of a VS2015 install

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by dsyme** [comment]
THe appveyor build is failing to build the FSharp.Core nuget package, though that's not failing the overall CI build.  From the end off the log it looks like FSharp.Core.nuspec is expecting the files to be placed into "v4.5" not "v4.0".  Looking at the layout used under ``C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0`` then ``v4.0`` is actually correct (we should mirror the  structure), so you may as well adjust the nuspec https://github.com/fsharp/fsharp/blob/fsharp4/FSharp.Core.Nuget/FSharp.Core.4.0.nuspec and https://github.com/fsharp/fsharp/blob/fsharp4/FSharp.Compiler.Tools.Nuget/FSharp.Compiler.Tools.4.0.nuspec as part of this PR until they build?

    [00:08:28] NuGet.exe : Could not find a part of the path 'C:\projects\fsharp\lib\bootstrap\signed\.NETFramework\v4.5\4.4.0.0'.

```
00:08:28] Attempting to build package from 'FSharp.Core.4.0.nuspec'.
[00:08:28] NuGet.exe : Could not find a part of the path 'C:\projects\fsharp\lib\bootstrap\signed\.NETFramework\v4.5\4.4.0.0'.
[00:08:28] At C:\projects\fsharp\appveyor.ps1:27 char:5
[00:08:28] +     & $nuget pack $nuspec -Version $version -NoDefaultExcludes
[00:08:28] +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:08:28]     + CategoryInfo          : NotSpecified: (Could not find ...\v4.5\4.4.0.0'.:String) [], RemoteException
[00:08:28]     + FullyQualifiedErrorId : NativeCommandError
[00:08:28]  
[00:08:28] Attempting to build package from 'FSharp.Compiler.Tools.4.0.nuspec'.
[00:08:28] NuGet.exe : Could not find a part of the path 'C:\projects\fsharp\lib\bootstrap\signed\.NETFramework\v4.5\4.4.0.0'.
[00:08:28] At C:\projects\fsharp\appveyor.ps1:27 char:5
[00:08:28] +     & $nuget pack $nuspec -Version $version -NoDefaultExcludes
[00:08:28] +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:08:28]     + CategoryInfo          : NotSpecified: (Could not find ...\v4.5\4.4.0.0'.:String) [], RemoteException
[00:08:28]     + FullyQualifiedErrorId : NativeCommandError
[00:08:28]  
[00:08:28] Packaging artifacts...
[00:08:28] OK
[00:08:33] Uploading artifact lib\release.zip (16 MB)...
[00:08:38] OK
[00:08:38] Build success
```

**Comment by forki** [comment]
let's see if that's better now

**Comment by forki** [comment]
and another trial. had to remove .NETFramework\v4.0\4.3.1.0\FSharp.Core.dll since it's overwritten by the 4.4 version

**Comment by ctaggart** [comment]
The NuSpec files shouldn't have the version on them. The Git branch takes care of that.
FSharp.Compiler.Tools.Nuget/FSharp.Compiler.Tools~~.4.0~~.nuspec
FSharp.Core.Nuget/FSharp.Core~~.4.0~~.nuspec

Make sure the Xamarin monikers have the trailing `10` instead of just `1` for Paket compatibility.
https://github.com/fsharp/fsharp/blob/master/FSharp.Core.Nuget/FSharp.Core.3.1.nuspec
```
    <!-- MonoAndroid, MonoTouch, Xamarin.iOS -->
    <file src="..\lib\release\monotouch\FSharp.Core.dll" target="lib\portable-net45+monoandroid10+monotouch10+xamarinios10\FSharp.Core.dll" />
    <file src="..\lib\release\monotouch\FSharp.Core.optdata" target="lib\portable-net45+monoandroid10+monotouch10+xamarinios10\FSharp.Core.optdata" />
    <file src="..\lib\release\monotouch\FSharp.Core.sigdata" target="lib\portable-net45+monoandroid10+monotouch10+xamarinios10\FSharp.Core.sigdata" />
    <file src="..\lib\release\monotouch\FSharp.Core.xml" target="lib\portable-net45+monoandroid10+monotouch10+xamarinios10\FSharp.Core.xml" />
```

**Comment by dsyme** [comment]
@ctaggart can you fix that up in subsequent PR?

**Comment by ctaggart** [comment]
Yes, hopefully before lunch.

**Pull request merged**
