### PR TITLE
Fix brew build: remove redundant explicit copy

### PR DESCRIPTION
**Pull request by dsyme**
Hopefully fixes https://github.com/fsharp/fsharp/issues/725

### CODE REVIEW

**Comment by dsyme** [comment]
PR to fix https://github.com/fsharp/fsharp/issues/725

**Comment by neutric** [comment]
@dsyme Homebrew build is green, thanks for the fix! As soon as 4.1.13 is tagged I can plug it in properly and ship the formula update.

**Comment by dsyme** [comment]
@neutric tagged!

**Comment by neutric** [comment]
@dsyme Shipped!

**Comment by dsyme** [comment]
Thanks!

**Pull request merged**
