### PR TITLE
Update targets.make

### PR DESCRIPTION
**Pull request by 7sharp9**
Added v11.00 target locations as the current mono's $(VisualStudioVersion) resolved to this.

### CODE REVIEW

**Comment by rneatherway** [comment]
Wow when did that happen! Is it necessary given that F# project files normally contain:

```
    <When Condition="'$(VisualStudioVersion)' == '11.0'">
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
```

**Comment by 7sharp9** [comment]
I have no idea what exists in the wild, the default F# console in XS will look like:

```
<Import Project="$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets" />
```

**Comment by dsyme** [comment]
Seems safe to add these, may as well

**Comment by dsyme** [comment]
Pushed tag 4.0.0.2

**Pull request merged**
